Example Project (#25)
* Example project
* Bug fixes for `@misk/components`
* Docker image `0.0.9`
* Bug fixes for `misk-web` script
* Live demo at `/examples/{slug}/demo/`
* Add example project building tests to Travis

diff --git a/docker/misk-web/misk-web b/docker/misk-web/misk-web
--- a/docker/misk-web/misk-web
+++ b/docker/misk-web/misk-web
@@ -21,9 +21,7 @@ usage() {
 
   -l    'lint' run Prettier linting
 
-  -o    compute a md5 hash over the current directory and stores in .hash file
-
-  -m    compute a md5 hash over the current directory and stores in .hash file, creates .hashdiff file if there is an existing hash
+  -m    compute a md5 hash over the current directory and stores in .hash file
         exclude patterns: cachedUrls, lib, node_modules, .hash
 
   -r    'refresh' local web/node_modules from Docker image /node_modules
@@ -78,6 +76,24 @@ hashDiff() {
     fi
 }
 
+hashDiffOutput() {
+    oldHash=$(echo "$1" | sed 's/[[:space:]]//g')
+    newHash=$(echo "$2" | sed 's/[[:space:]]//g')
+    if [ "$oldHash" = "$newHash" ]; then
+        echo "${oldHash} ${newHash} false"
+    else
+        echo "${oldHash} ${newHash} true"
+    fi
+}
+
+hashDiffFiles() {
+    oldHashFile="$1"
+    newHashFile="$2"
+    [ -f "$oldHashFile" ] || echo "true"
+    [ -f "$newHashFile" ] || echo "true"
+    hashDiffOutput "$(cat "$oldHashFile")" "$(cat "$newHashFile")"
+}
+
 stashNodeModules() {
     echo "[STASH] Removing tab node_modules and linking to node_modules from Docker image"
     # Remove any previous node_modules links or directories
@@ -85,11 +101,16 @@ stashNodeModules() {
     rm -rf ./node_modules
     # Link to cached node_modules in Docker image
     ln -s /node_modules .
+    # Put @misk/dev/tsconfig.base.json where it needs to be
+    mkdir -p /web/node_modules/@misk/dev/
+    cp /node_modules/@misk/dev/tsconfig.base.json /web/node_modules/@misk/dev/
 }
 
 refreshNodeModules() {
+    # Refresh node_modules if hash doesn't match, not in CI environments
+    [ -z "$CI" ] && [ -d ${WEB}/node_modules ] && hashDiffFiles ${WEB}/node_modules/.hash /node_modules/.hash | grep -Fq "true" && echo "[INVALIDATE] Invalidate local web/node_modules/" && echo "" && rm -rf ${WEB}/node_modules
     # Install local web/node_modules if not already present, not in CI environments
-    [ ! -d ${WEB}/node_modules ] && ! printenv | grep -q "CI" && echo "[REFRESH] Updating local web/node_modules/ from Docker image" && cp -r /node_modules ${WEB}/node_modules
+    [ -z "$CI" ] && [ ! -d ${WEB}/node_modules ] && echo "[REFRESH] Installing local web/node_modules/ from Docker image" && echo "" && cp -rf /node_modules ${WEB}/node_modules
 }
 
 restoreNodeModules() {
@@ -134,7 +155,7 @@ reset() {
     HD="false"
 }
 
-while getopts "h?abcdglomrwxz:" opt; do
+while getopts "h?abcdglmrwxz:" opt; do
     case "$opt" in
         h|\?)   usage && exit 0   ;;
         a)      LABEL="[BUILD ALL]" && CMD='yarn build' && runCmd && reset   ;;
@@ -143,9 +164,8 @@ while getopts "h?abcdglomrwxz:" opt; do
         d)      LABEL="[DEV]" && CMD='yarn start' && runCmd && reset   ;;
         g)      LABEL="[CI-BUILD]" && HD="true" && CMD='yarn ci-build' && runCmd && reset   ;;
         l)      LABEL="[LINT]" && CMD='yarn run lint' && runCmd && reset  ;;
-        o)      LABEL="[MD5 HASH]" && CMD='hashDir | tee .hash' && runCmd && reset   ;;
-        m)      LABEL="[MD5 HASHDIFF]" && CMD='hashDiff' && runCmd && reset   ;;
-        r)      restoreNodeModules && reset    ;;
+        m)      hashDir | tee .hash   ;;
+        r)      refreshNodeModules && restoreNodeModules && reset    ;;
         w)      LABEL="[ALT WEB LOCATION]" && WEB="${OPTARG}" && reset    ;;
         x)      LABEL="[HD=\"true\"]" && HD="true"    ;;
         z)      LABEL="[CMD]" && CMD="${OPTARG}" && runCmd && reset   ;;
